### ISSUE TITLE
[BUG] `gtk4::GestureClick::connect_unpaired_release` panics

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk4-rs#1046]
```
thread 'main' panicked at 'assertion failed: !ptr.is_null()', /home/lollo/.../Geopard/_build/cargo-home/git/checkouts/gtk-rs-core-dcd88e7dfd7b37a9/4b519db/glib/src/boxed.rs:448:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: <glib::boxed::Boxed<T,MM> as glib::translate::FromGlibPtrBorrow<*mut T>>::from_glib_borrow
             at ./.../Geopard/_build/cargo-home/git/checkouts/gtk-rs-core-dcd88e7dfd7b37a9/4b519db/glib/src/boxed.rs:448:9
   4: glib::translate::from_glib_borrow
             at ./.../Geopard/_build/cargo-home/git/checkouts/gtk-rs-core-dcd88e7dfd7b37a9/4b519db/glib/src/translate.rs:1477:5
   5: <gdk4::auto::event_sequence::EventSequence as glib::translate::FromGlibPtrBorrow<*mut gdk4_sys::GdkEventSequence>>::from_glib_borrow
             at ./.../Geopard/_build/cargo-home/git/checkouts/gtk-rs-core-dcd88e7dfd7b37a9/4b519db/glib/src/boxed.rs:186:32
   6: glib::translate::from_glib_borrow
             at ./.../Geopard/_build/cargo-home/git/checkouts/gtk-rs-core-dcd88e7dfd7b37a9/4b519db/glib/src/translate.rs:1477:5
   7: gtk4::auto::gesture_click::GestureClick::connect_unpaired_release::unpaired_release_trampoline
             at ./.../Geopard/_build/cargo-home/git/checkouts/gtk4-rs-e74ad56283dfeb5e/713bd29/gtk4/src/auto/gesture_click.rs:138:18
```

**Comment by sdroege** [comment]
Please provide a testcase to reproduce it, or at least a full backtrace.

**Comment by qarmin** [comment]
Not minimal but after few click at button app crashes
```
use gtk4::prelude::*;

struct GuiData {
    window : gtk4::ApplicationWindow,
    button : gtk4::Button,
    gc_button: gtk4::GestureClick
}
impl GuiData {
    pub fn new_with_application(application: &gtk4::Application) -> Self{
    let window = gtk4::ApplicationWindow::new(application);


        let button =  gtk4::Button::with_label("TEST");
        let gc_button =  gtk4::GestureClick::new();
        button.add_controller(&gc_button);

        window.set_child(Some(&button));
        window.set_default_size(300, 300);

        GuiData{
            window,
            button,
            gc_button
        }
    }
}

fn main() {
    let application = gtk4::Application::builder().build();
    application.connect_activate(move |application| {
        let gui_data = GuiData::new_with_application(&application);

        // gui_data.gc_button

        gui_data.gc_button.set_button(1);
        gui_data.gc_button.connect_pressed(|a,b,c,d|{
           println!("PRESSED {} - {:?} - {} - {} - {}",a.current_button(),a,b,c,d);
        });
        gui_data.gc_button.connect_unpaired_release(|a,b,c,d,e|{
            println!("UNPAIRED RELEASE {} - {:?} - {} - {} - {}",a.current_button(),a,b,c,d);
        });
        gui_data.gc_button.connect_released(|a,b,c,d|{
            println!("RELEASED {} - {:?} - {} - {} - {}",a.current_button(),a,b,c,d);
        });

        gui_data.window.show();
    });
    application.run();
}

```

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk4-rs/pull/1050
