### ISSUE TITLE
[BUG] PopoverMenu.show() causes crash

### ISSUE THREAD

**Issue by qarmin** [gtk-rs/gtk4-rs#1123]
```
  Host: rafal-H87M-D3H Kernel: 5.15.0-47-generic x86_64 bits: 64
    compiler: gcc v: 11.2.0 Desktop: GNOME 42.4 tk: GTK 3.24.33 wm: gnome-shell
    dm: GDM3 Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
GTK 4.6.6
```
```
RUST_BACKTRACE=full RUSTFLAGS=-Zsanitizer=address RUSTDOCFLAGS=-Zsanitizer=address cargo run  -Zbuild-std --target x86_64-unknown-linux-gnu
```

**Bug description**

```
    let thing: Option<&gio::MenuModel> = None;
    let thing = PopoverMenu::from_model(thing); // PopoverMenu
    thing.show();
```
cause crash
```
(crash_thing:58789): Gtk-WARNING **: 20:16:38.774: Calling gtk_widget_realize() on a widget that isn't inside a toplevel window is not going to work very well. Widgets must be inside a toplevel container before realizing them.

(crash_thing:58789): Gtk-CRITICAL **: 20:16:38.774: gtk_widget_get_native: assertion 'GTK_IS_WIDGET (widget)' failed

(crash_thing:58789): Gtk-CRITICAL **: 20:16:38.774: gtk_native_get_surface: assertion 'GTK_IS_NATIVE (self)' failed

(crash_thing:58789): Gdk-CRITICAL **: 20:16:38.774: gdk_surface_new_popup: assertion 'GDK_IS_SURFACE (parent)' failed
AddressSanitizer:DEADLYSIGNAL
=================================================================
==58789==ERROR: AddressSanitizer: SEGV on unknown address 0xfffffffffffffff8 (pc 0x7fb5ed3958b8 bp 0x6290001a6210 sp 0x7ffecc1ee580 T0)
==58789==The signal is caused by a WRITE memory access.
    #0 0x7fb5ed3958b8  (/lib/x86_64-linux-gnu/libgtk-4.so.1+0x1f58b8) (BuildId: dc84b6fc2a71f8f0ed7a524c19ec980c97206e41)
    #1 0x7fb5ecdae63f in g_signal_emit_valist (/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x3263f) (BuildId: 8a28a4aa6836963e7f50074984225cc07392b5b4)
    #2 0x7fb5ecdae7a2 in g_signal_emit (/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x327a2) (BuildId: 8a28a4aa6836963e7f50074984225cc07392b5b4)
    #3 0x7fb5ed48f554 in gtk_widget_realize (/lib/x86_64-linux-gnu/libgtk-4.so.1+0x2ef554) (BuildId: dc84b6fc2a71f8f0ed7a524c19ec980c97206e41)
    #4 0x7fb5ed397048  (/lib/x86_64-linux-gnu/libgtk-4.so.1+0x1f7048) (BuildId: dc84b6fc2a71f8f0ed7a524c19ec980c97206e41)
    #5 0x7fb5ecdae63f in g_signal_emit_valist (/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x3263f) (BuildId: 8a28a4aa6836963e7f50074984225cc07392b5b4)
    #6 0x7fb5ecdae7a2 in g_signal_emit (/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x327a2) (BuildId: 8a28a4aa6836963e7f50074984225cc07392b5b4)
    #7 0x7fb5ed48daad in gtk_widget_show (/lib/x86_64-linux-gnu/libgtk-4.so.1+0x2edaad) (BuildId: dc84b6fc2a71f8f0ed7a524c19ec980c97206e41)
    #8 0x55737f2e858b in _$LT$O$u20$as$u20$gtk4..auto..widget..WidgetExt$GT$::show::h2ff57c7201099a10 /home/rafal/.cargo/git/checkouts/gtk4-rs-e74ad56283dfeb5e/58c7187/gtk4/src/auto/widget.rs:1909:13
    #9 0x55737f2f44e8 in crash_thing::crashes::h8b12989a55ff5b38 /home/rafal/Projekty/Rust/gtk_rs_fuzzer/Project/src/main.rs:44:5
    #10 0x55737f2f10aa in crash_thing::main::_$u7b$$u7b$closure$u7d$$u7d$::h378cbb8470b0d669 /home/rafal/Projekty/Rust/gtk_rs_fuzzer/Project/src/main.rs:29:13
    #11 0x55737f2f05f1 in _$LT$O$u20$as$u20$gio..auto..application..ApplicationExt$GT$::connect_activate::activate_trampoline::h6b19c93516c04259 /home/rafal/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/3221869/gio/src/auto/application.rs:556:13
    #12 0x7fb5ecd90d2e in g_closure_invoke (/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x14d2e) (BuildId: 8a28a4aa6836963e7f50074984225cc07392b5b4)
    #13 0x7fb5ecdacb75  (/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x30b75) (BuildId: 8a28a4aa6836963e7f50074984225cc07392b5b4)
    #14 0x7fb5ecdae553 in g_signal_emit_valist (/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x32553) (BuildId: 8a28a4aa6836963e7f50074984225cc07392b5b4)
    #15 0x7fb5ecdae7a2 in g_signal_emit (/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x327a2) (BuildId: 8a28a4aa6836963e7f50074984225cc07392b5b4)
    #16 0x7fb5ecebca37  (/lib/x86_64-linux-gnu/libgio-2.0.so.0+0xe0a37) (BuildId: c3778bad9d8a3642cc51d453c07da246154dd4d7)
    #17 0x7fb5ecebcc15 in g_application_run (/lib/x86_64-linux-gnu/libgio-2.0.so.0+0xe0c15) (BuildId: c3778bad9d8a3642cc51d453c07da246154dd4d7)
    #18 0x55737f2fe3eb in _$LT$O$u20$as$u20$gio..application..ApplicationExtManual$GT$::run_with_args::h74f6a2d8a88760e3 /home/rafal/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/3221869/gio/src/application.rs:35:13
    #19 0x55737f2fe96f in _$LT$O$u20$as$u20$gio..application..ApplicationExtManual$GT$::run::h1d98613aa34101b8 /home/rafal/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/3221869/gio/src/application.rs:28:9
    #20 0x55737f2f4111 in crash_thing::main::h206ae7446c449f11 /home/rafal/Projekty/Rust/gtk_rs_fuzzer/Project/src/main.rs:36:5
    #21 0x55737f2eef3a in core::ops::function::FnOnce::call_once::ha94001f3f257c38c /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5
    #22 0x55737f2f0724 in std::sys_common::backtrace::__rust_begin_short_backtrace::hed5d44176279b41e /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18
    #23 0x55737f2e6fa3 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h3670eb56e90237b7 /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:145:18
    #24 0x55737fa6525d in core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::hb370384f83339e3c /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:280:13
    #25 0x55737fb4b39e in std::panicking::try::do_call::hf234557b23354cf3 /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
    #26 0x55737fb5cf9a in __rust_try std.a9c15bf2-cgu.7
    #27 0x55737fb499a2 in std::panicking::try::h7dfbec646aff0147 /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
    #28 0x55737f8d8e89 in std::panic::catch_unwind::hf8c789c075c9faff /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
    #29 0x55737f95ca6b in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h4e3bbcbadadd82e1 /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:128:48
    #30 0x55737fb4b01d in std::panicking::try::do_call::h9a17123ed7c96e68 /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
    #31 0x55737fb5cf9a in __rust_try std.a9c15bf2-cgu.7
    #32 0x55737fb4a69b in std::panicking::try::hdfcf65233d49fb1e /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
    #33 0x55737f8d8b69 in std::panic::catch_unwind::h1d15d7e951d3dde3 /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
    #34 0x55737f95c3d9 in std::rt::lang_start_internal::h40e3114cb60b6d03 /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:128:20
    #35 0x55737f2e6f05 in std::rt::lang_start::h3a6a1a0e7786a54a /home/rafal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:144:17
    #36 0x55737f2f81eb in main (/home/rafal/Projekty/Rust/gtk_rs_fuzzer/Project/target/x86_64-unknown-linux-gnu/debug/crash_thing+0x35d1eb) (BuildId: a58ba299626da4216bdd088965d3609dae27782b)
    #37 0x7fb5ec93ad8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #38 0x7fb5ec93ae3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #39 0x55737f24b274 in _start (/home/rafal/Projekty/Rust/gtk_rs_fuzzer/Project/target/x86_64-unknown-linux-gnu/debug/crash_thing+0x2b0274) (BuildId: a58ba299626da4216bdd088965d3609dae27782b)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libgtk-4.so.1+0x1f58b8) (BuildId: dc84b6fc2a71f8f0ed7a524c19ec980c97206e41) 

```

Issue found by fuzzer - https://github.com/qarmin/gtk-rs-fuzzer

**Comment by sdroege** [comment]
This is a bug in GTK, please report it there. Ideally with a C testcase: exactly the same code in C should reproduce the same problem.
