### ISSUE TITLE
[BUG] Assertion failure getting surface from ApplicationWindow

### ISSUE THREAD

**Issue by antangelo** [gtk-rs/gtk4-rs#1291]
**Bug description**

Calling `window.surface()` on an ApplicationWindow panics with the following assertion failure:

```
thread 'main' panicked at 'assertion failed: ::glib::types::instance_of::<Self>(ptr as *const _)', /home/user/.cargo/git/checkouts/gtk4-rs-e74ad56283dfeb5e/f3b2ca8/gdk4/src/auto/surface.rs:16:1
```

This minimal example uses an ApplicationWindow, but I've also run into the same behavior using a Window widget.

```Rust
use gtk::prelude::*;

fn app_activate(app: &gtk::Application) {
    let window = gtk::ApplicationWindow::builder()
        .application(app)
        .title("Surface Test")
        .build();

    let _surface = window.surface();

    window.show();
}

fn main() {
    let app = gtk::Application::builder()
        .application_id("com.github.antangelo.test")
        .build();

    app.connect_activate(app_activate);
    app.run();
}
```

**Backtrace**

```
    Skipping git submodule `https://github.com/gtk-rs/gir` due to update strategy in .gitmodules
    Skipping git submodule `https://github.com/gtk-rs/gir-files` due to update strategy in .gitmodules
    Skipping git submodule `https://github.com/gtk-rs/gir` due to update strategy in .gitmodules
    Skipping git submodule `https://github.com/gtk-rs/gir-files` due to update strategy in .gitmodules
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rust-gtk4-bug`
thread 'main' panicked at 'assertion failed: ::glib::types::instance_of::<Self>(ptr as *const _)', /home/user/.cargo/git/checkouts/gtk4-rs-e74ad56283dfeb5e/f3b2ca8/gdk4/src/auto/surface.rs:16:1
stack backtrace:
   0:     0x562524716b50 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562524716b50 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562524716b50 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x562524716b50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56252473063e - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x562524714b85 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x562524716915 - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x562524716915 - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x56252471801f - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x562524717d5a - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x562524718718 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x562524718471 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:577:13
  12:     0x562524716ffc - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x5625247181d2 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x5625246dd033 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x5625246dd10d - core::panicking::panic::h9ced3cf2f605ba6a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
  16:     0x5625246e4310 - <gdk4::auto::surface::Surface as glib::translate::FromGlibPtrNone<*mut gdk4_sys::GdkSurface>>::from_glib_none::hfcd96648293a08f6
                               at /home/user/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/dee1d23/glib/src/object.rs:881:17
  17:     0x5625246e43ae - glib::translate::from_glib_none::h1cfbbe21e40377b5
                               at /home/user/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/dee1d23/glib/src/translate.rs:1622:5
  18:     0x5625246e10bd - <O as gtk4::auto::native::NativeExt>::surface::ha7e768a99bfc3a14
                               at /home/user/.cargo/git/checkouts/gtk4-rs-e74ad56283dfeb5e/f3b2ca8/gtk4/src/auto/native.rs:59:18
  19:     0x5625246dea44 - rust_gtk4_bug::app_activate::h1d69c3f0c80b927d
                               at /home/user/Projects/rust-gtk4-bug/src/main.rs:9:20
  20:     0x5625246dda08 - core::ops::function::Fn::call::h76cbf05ee77acbf3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:78:5
  21:     0x5625246dd652 - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::h94afbddafee05faa
                               at /home/user/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/dee1d23/gio/src/auto/application.rs:538:13
  22:     0x7ff167326210 - g_closure_invoke
  23:     0x7ff167353eb8 - <unknown>
  24:     0x7ff167343f85 - g_signal_emit_valist
  25:     0x7ff167344214 - g_signal_emit
  26:     0x7ff1667e1389 - <unknown>
  27:     0x7ff1667ec6dc - g_application_run
  28:     0x5625246de678 - <O as gio::application::ApplicationExtManual>::run_with_args::h4b236e3fb7c99bb6
                               at /home/user/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/dee1d23/gio/src/application.rs:37:13
  29:     0x5625246de786 - <O as gio::application::ApplicationExtManual>::run::h7f0f1aa0534db75c
                               at /home/user/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/dee1d23/gio/src/application.rs:30:9
  30:     0x5625246deb78 - rust_gtk4_bug::main::h72c34ae913ed65d7
                               at /home/user/Projects/rust-gtk4-bug/src/main.rs:20:5
  31:     0x5625246dda3b - core::ops::function::FnOnce::call_once::h210f0dc10ceaae8a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  32:     0x5625246dd91e - std::sys_common::backtrace::__rust_begin_short_backtrace::hffbbf49711cc52cb
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
  33:     0x5625246de9b1 - std::rt::lang_start::{{closure}}::h310ecbeff4e38c5e
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:166:18
  34:     0x562524712d1b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h072eb4cd8da964ba
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:286:13
  35:     0x562524712d1b - std::panicking::try::do_call::h8eca204fe9266946
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  36:     0x562524712d1b - std::panicking::try::h12574e1b7b2cbacb
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  37:     0x562524712d1b - std::panic::catch_unwind::hf71522d4448329d6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  38:     0x562524712d1b - std::rt::lang_start_internal::{{closure}}::h65b66ac9bff580f8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:48
  39:     0x562524712d1b - std::panicking::try::do_call::hfff61e33ca3db9f1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  40:     0x562524712d1b - std::panicking::try::he48c8ecead279cad
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  41:     0x562524712d1b - std::panic::catch_unwind::hd510a26bfc950ccc
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  42:     0x562524712d1b - std::rt::lang_start_internal::hc680b25eab888da9
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:20
  43:     0x5625246de98a - std::rt::lang_start::hb365431a2d0d5b08
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:165:17
  44:     0x5625246debce - main
  45:     0x7ff16640b290 - <unknown>
  46:     0x7ff16640b34a - __libc_start_main
  47:     0x5625246dd375 - _start
  48:                0x0 - <unknown>
```

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gtk-rs-core/pull/953 makes this assertion a bit clearer.

The solution here is to first call `WidgetExt::realize(&window);` before getting the surface as otherwise there is no surface. As such, the function should be marked as `nullable` and return an `Option`. @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
> [gtk-rs/gtk-rs-core#953](https://github.com/gtk-rs/gtk-rs-core/pull/953) makes this assertion a bit clearer.
> 
> The solution here is to first call `WidgetExt::realize(&window);` before getting the surface as otherwise there is no surface. As such, the function should be marked as `nullable` and return an `Option`. @bilelmoussaoui

Wouldn't this be more considered a programmer error and the C side of things should have an assertion to ensure the widget is realized first?

**Comment by sdroege** [comment]
That would be the other option but apparently it's not an assertion in C

**Comment by bilelmoussaoui** [comment]
Upstream made the renderer/surface functions in GtkNative nullabe, see https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.NativeExt.html#method.surface

So this one is fixed
