### ISSUE TITLE
[BUG] v0.6.0 segfaults in `gtk::ConstraintLayout::add_constraints_from_description`

### ISSUE THREAD

**Issue by andy128k** [gtk-rs/gtk4-rs#1297]
**add_constraints_from_description causes SEGFAULT**

```rust
    impl ObjectImpl for PSRecordViewItem {
        fn constructed(&self) {
            self.parent_constructed();

            let layout = gtk::ConstraintLayout::new();
            self.obj().set_layout_manager(Some(layout.clone()));

            layout
                .add_constraints_from_description(
                    &[
                        "H:|-[icon(==30)]-[name]-[strength(==50)]-[share(==50)]-|",
                        "V:|-[icon]-|",
                        "V:|-[name]-|",
                        "V:|-[strength]-|",
                        "V:|-[share]-|",
                    ] as &[&str],
                    4,
                    0,
                    [
                        ("icon", self.icon.upcast_ref::<gtk::Widget>()),
                        ("name", self.name.upcast_ref()),
                        ("strength", self.strength.upcast_ref()),
                        ("share", self.open.upcast_ref()),
                    ],
                )
                .expect("layout is ok");

    .....
```

**Backtrace**

```
#1  0x00007ffff79461f7 in gtk_constraint_vfl_parser_parse_line
    (parser=parser@entry=0x5555568ec8e0, buffer=buffer@entry=0x0, len=len@entry=-1, error=error@entry=0x7fffffff9880)
    at ../../../gtk/gtkconstraintvflparser.c:828
#2  0x00007ffff773fe23 in gtk_constraint_layout_add_constraints_from_descriptionv
    (layout=0x5555568ea420 [GtkConstraintLayout], lines=0x5555568d3600, n_lines=6, hspacing=<optimized out>, vspacing=<optimized out>, views=0x7fffe00b59e0 = {...}, error=0x7fffffff9ee0) at ../../../gtk/gtkconstraintlayout.c:2056
#3  0x0000555555652aed in gtk4::constraint_layout::{impl#0}::add_constraints_from_description::{closure#0}<gtk4::auto::widget::Widget, &[&str], [(&str, &gtk4::auto::widget::Widget); 4]> (lines=...) at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.6.0/src/constraint_layout.rs:36
#4  0x00005555556b6f25 in glib::collections::strv::{impl#51}::run_with_strv<core::result::Result<alloc::vec::Vec<gtk4::auto::constraint::Constraint, alloc::alloc::Global>, glib::error::Error>, gtk4::constraint_layout::{impl#0}::add_constraints_from_description::{closure_env#0}<gtk4::auto::widget::Widget, &[&str], [(&str, &gtk4::auto::widget::Widget); 4]>> (self=0x7fffffff9cd0, f=...)
    at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.17.0/src/collections/strv.rs:1044
#5  0x00005555556b6db8 in glib::collections::strv::{impl#50}::run_with_strv<core::result::Result<alloc::vec::Vec<gtk4::auto::constraint::Constraint, alloc::alloc::Global>, glib::error::Error>, gtk4::constraint_layout::{impl#0}::add_constraints_from_description::{closure_env#0}<gtk4::auto::widget::Widget, &[&str], [(&str, &gtk4::auto::widget::Widget); 4]>>Python Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x5555568ec

    (self=#6  0x00005555556b6ce3 in glib::collections::strv::{impl#54}::run_with_strv<core::result::Result<alloc::vec::Vec<gtk4::auto::constraint::Constraint, alloc::alloc::Global>, glib::error::Error>, gtk4::constraint_layout::{impl#0}::add_constraints_from_description::{closure_env#0}<gtk4::auto::widget::Widget, &[&str], [(&str, &gtk4::auto::widget::Widget); 4]>> (self=..., f=...)
    at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.17.0/src/collections/strv.rs:1136
#7  0x000055555570a5c3 in gtk4::auto::constraint_layout::ConstraintLayout::add_constraints_from_description<gtk4::auto::widget::Widget, &[&str], [(&str, &gtk4::auto::widget::Widget); 4]> (self=0x7fffffffa1f8, lines=..., hspacing=4, vspacing=0, views=...)
    at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.6.0/src/constraint_layout.rs:35
#8  0x0000555555659f70 in password_storage::ui::record_view::item::imp::{impl#0}::constructed (self=0x555555c50280) at src/ui/record_view/item.rs:47
#9  0x000055555566f781 in glib::subclass::object::constructed<password_storage::ui::record_view::item::imp::PSRecordViewItem> (obj=0x555555c50410)
    at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.17.0/src/subclass/object.rs:116
#10 0x00007ffff7f4fe06 in g_object_new_internal (class=class@entry=0x5555568eac60, params=params@entry=0x0, n_params=n_params@entry=0)
    at ../../../gobject/gobject.c:2279
#11 0x00007ffff7f513fc in g_object_new_with_properties
    (object_type=0x5555568ea380 [PSRecordViewItem/GtkWidget/GInitiallyUnowned], n_properties=<optimized out>, names=0x7fffffffac60, values=0x7fffffffacf0)
    at ../../../gobject/gobject.c:2391
#12 0x0000555555890de3 in glib::object::Object::new_internal (type_=..., properties=...) at src/object.rs:1473
#13 0x000055555589030a in glib::object::Object::with_mut_values (type_=..., properties=...) at src/object.rs:1406
#14 0x00005555556666ec in glib::object::ObjectBuilder<password_storage::ui::record_view::item::PSRecordViewItem>::build<password_storage::ui::record_view::item::PSRecordViewItem> (self=...) at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.17.0/src/object.rs:1555
#15 0x0000555555709030 in password_storage::ui::record_view::item::PSRecordViewItem::new () at src/ui/record_view/item.rs:178
#16 0x0000555555712ed6 in password_storage::ui::record_view::item_factory::item_factory::{closure#0} (_factory=0x7fffffffb4e8, list_item=0x7fffffffb4f0)
    at src/ui/record_view/item_factory.rs:22
#17 0x0000555555735a39 in gtk4::signal_list_item_factory::{impl#0}::connect_setup::setup_trampoline<password_storage::ui::record_view::item_factory::item_factory::{closure_env#0}> (this=0x555555bb2ac0, listitem=0x55555691eea0, f=0x555555bbc6d0)
    at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.6.0/src/signal_list_item_factory.rs:52
#18 0x00007ffff7f4d611 in g_cclosure_marshal_VOID__OBJECTv
    (closure=0x555555bbc710, return_value=<optimized out>, instance=0x555555bb2ac0, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555bbcca0) at ../../../gobject/gmarshal.c:1910
#19 0x00007ffff7f4a5a9 in _g_closure_invoke_va
    (closure=closure@entry=0x555555bbc710, return_value=return_value@entry=0x0, instance=instance@entry=0x555555bb2ac0, args=args@entry=0x7fffffffb760, n_params=1, param_types=0x555555bbcca0) at ../../../gobject/gclosure.c:895
#20 0x00007ffff7f63bbf in g_signal_emit_valist (instance=0x555555bb2ac0, signal_id=173, detail=<optimized out>, var_args=var_args@entry=0x7fffffffb760)
    at ../../../gobject/gsignal.c:3456
#21 0x00007ffff7f63dbf in g_signal_emit (instance=instance@entry=0x555555bb2ac0, signal_id=<optimized out>, detail=detail@entry=0)
    at ../../../gobject/gsignal.c:3606
```

----

Also I've noticed that `IntoStrV` is not friendly with static arrays.

I've got an error:
```
the trait `IntoStrV` is not implemented for `&[&str; 5]`
```

that's why I am forced to cast it like `as &[&str]`.

**Comment by andy128k** [comment]
@sdroege Here it is.

```rust
use gtk::{gio, prelude::*};
use std::process::Termination;

fn main() -> impl Termination {
    let app = gtk::Application::new(
        Some("io.github.andy128k.test-gtk-rs-sefault"),
        gio::ApplicationFlags::FLAGS_NONE,
    );
    app.connect_activate(|app| {
        let wnd = gtk::ApplicationWindow::new(app);

        let layout = gtk::ConstraintLayout::new();
        wnd.set_layout_manager(Some(layout.clone()));

        let icon = gtk::Image::builder().icon_name("new-document").build();
        icon.set_parent(&wnd);

        let name = gtk::Label::new(Some("Demo"));
        name.set_parent(&wnd);

        layout
            .add_constraints_from_description(
                &["V:|-[icon]-|", "V:|-[name]-|"] as &[&str],
                4,
                0,
                [
                    ("icon", icon.upcast_ref::<gtk::Widget>()),
                    ("name", name.upcast_ref()),
                ],
            )
            .expect("layout is ok");

        wnd.show();
    });
    app.run()
}
```

--- 

```
Thread 1 "test-gtk-rs-seg" received signal SIGSEGV, Segmentation fault.
__strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-sse2.S:142
142	../sysdeps/x86_64/multiarch/strlen-sse2.S: No such file or directory.
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-sse2.S:142
#1  0x00007ffff79461f7 in gtk_constraint_vfl_parser_parse_line
    (parser=parser@entry=0x555555716aa0, buffer=buffer@entry=0x0, len=len@entry=-1, error=error@entry=0x7fffffffc640)
    at ../../../gtk/gtkconstraintvflparser.c:828
#2  0x00007ffff773fe23 in gtk_constraint_layout_add_constraints_from_descriptionv
    (layout=0x55555573d490 [GtkConstraintLayout], lines=0x7fffffffc870, n_lines=3, hspacing=<optimized out>, vspacing=<optimized out>, views=0x55555577fc00 = {...}, error=0x7fffffffcbb0) at ../../../gtk/gtkconstraintlayout.c:2056
#3  0x0000555555567bad in gtk4::constraint_layout::{impl#0}::add_constraints_from_description::{closure#0}<gtk4::auto::widget::Widget, &[&str], [(&str, &gtk4::auto::widget::Widget); 2]> (lines=...) at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.6.0/src/constraint_layout.rs:36
#4  0x000055555556699b in glib::collections::strv::{impl#54}::run_with_strv<core::result::Result<alloc::vec::Vec<gtk4::auto::constraint::Constraint, alloc::alloc::Global>, glib::error::Error>, gtk4::constraint_layout::{impl#0}::add_constraints_from_description::{closure_env#0}<gtk4::auto::widget::Widget, &[&str], [(&str, &gtk4::auto::widget::Widget); 2]>> (self=..., f=...) at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.17.0/src/collections/strv.rs:1131
#5  0x000055555556577b in gtk4::auto::constraint_layout::ConstraintLayout::add_constraints_from_description<gtk4::auto::widget::Widget, &[&str], [(&str, &gtk4::auto::widget::Widget); 2]> (self=0x7fffffffcda0, lines=..., hspacing=4, vspacing=0, views=...)
    at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.6.0/src/constraint_layout.rs:35
#6  0x0000555555568121 in test_gtk_rs_segfault::main::{closure#0} (app=0x7fffffffd3d8) at src/main.rs:21
#7  0x0000555555565811 in gio::auto::application::{impl#3}::connect_activate::activate_trampoline<gtk4::auto::application::Application, test_gtk_rs_segfault::main::{closure_env#0}> (this=0x55555560b0e0, f=0x1) at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.17.0/src/auto/application.rs:538
#11 0x00007ffff7f63dbf in <emit signal ??? on instance 0x55555560b0e0 [GtkApplication]>
    (instance=instance@entry=0x55555560b0e0, signal_id=<optimized out>, detail=detail@entry=0) at ../../../gobject/gsignal.c:3606
    #8  0x00007ffff7f4a3b0 in g_closure_invoke
    (closure=0x55555560e1d0, return_value=return_value@entry=0x0, n_param_values=1, param_values=param_values@entry=0x7fffffffd590, invocation_hint=invocation_hint@entry=0x7fffffffd510) at ../../../gobject/gclosure.c:832
    #9  0x00007ffff7f5d076 in signal_emit_unlocked_R
    (node=node@entry=0x555555604dc0, detail=detail@entry=0, instance=instance@entry=0x55555560b0e0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd590) at ../../../gobject/gsignal.c:3796
    #10 0x00007ffff7f63bf5 in g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd710) at ../../../gobject/gsignal.c:3549
#12 0x00007ffff73db0c3 in g_application_activate (application=application@entry=0x55555560b0e0 [GtkApplication]) at ../../../gio/gapplication.c:2312
#13 0x00007ffff73db438 in g_application_real_local_command_line
    (application=0x55555560b0e0 [GtkApplication], arguments=0x7fffffffd858, exit_status=0x7fffffffd854) at ../../../gio/gapplication.c:1148
#14 0x00007ffff73db5c6 in g_application_run (application=0x55555560b0e0 [GtkApplication], argc=<optimized out>, argv=<optimized out>)
    at ../../../gio/gapplication.c:2542
#15 0x0000555555561eae in gio::application::{impl#0}::run_with_args<gtk4::auto::application::Application, alloc::string::String>
    (self=0x7fffffffda30, args=...) at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.17.0/src/application.rs:37
#16 0x0000555555561fc9 in gio::application::{impl#0}::run<gtk4::auto::application::Application> (self=0x7fffffffda30)
    at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.17.0/src/application.rs:30
#17 0x0000555555565065 in test_gtk_rs_segfault::main () at src/main.rs:35
```
```

**Comment by andy128k** [comment]
FR is created too https://github.com/gtk-rs/gtk-rs-core/issues/976

**Comment by sdroege** [comment]
Thanks, I'll take a look after getting gstreamer-rs released :)
