### ISSUE TITLE
Panic if `WaylandToplevel::export_handle` fails

### ISSUE THREAD

**Issue by YaLTeR** [gtk-rs/gtk4-rs#1565]
**Bug description**

It can fail for example if the compositor doesn't implement the xdg-foreign protocol. In this case it returns an error from the task: https://gitlab.gnome.org/GNOME/gtk/-/blob/8ac8a027b29a7b9baaac6d7cbb8e3e0621d02cdf/gdk/wayland/gdktoplevel-wayland.c#L1827

**Backtrace**

```
thread 'main' panicked at /var/home/yalter/source/rs/ashpd/ashpd-demo/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/glib-0.18.5/src/gstring.rs:1990:9:
assertion failed: !ptr.is_null()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:127:5
   3: <glib::gstring::GString as glib::translate::FromGlibPtrBorrow<*const u8>>::from_glib_borrow
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/glib-0.18.5/src/gstring.rs:1990:9
   4: glib::translate::from_glib_borrow
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/glib-0.18.5/src/translate.rs:1640:5
   5: <glib::gstring::GString as glib::translate::FromGlibPtrBorrow<*const i8>>::from_glib_borrow
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/glib-0.18.5/src/gstring.rs:2006:9
   6: glib::translate::from_glib_borrow
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/glib-0.18.5/src/translate.rs:1640:5
   7: gdk4_wayland::auto::wayland_toplevel::WaylandToplevel::export_handle::callback_func
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gdk4-wayland-0.7.2/src/auto/wayland_toplevel.rs:41:51
   8: export_handle_done
             at /usr/src/debug/gtk4-4.12.4-1.fc39.x86_64/redhat-linux-build/../gdk/wayland/gdktoplevel-wayland.c:2487:3
   9: g_task_return_now
             at /usr/src/debug/glib2-2.78.3-1.1.tracy1.fc39.x86_64/redhat-linux-build/../gio/gtask.c:1371:7
  10: complete_in_idle_cb
             at /usr/src/debug/glib2-2.78.3-1.1.tracy1.fc39.x86_64/redhat-linux-build/../gio/gtask.c:1385:3
  11: g_idle_dispatch
             at /usr/src/debug/glib2-2.78.3-1.1.tracy1.fc39.x86_64/redhat-linux-build/../glib/gmain.c:6334:15
  12: g_main_dispatch
             at /usr/src/debug/glib2-2.78.3-1.1.tracy1.fc39.x86_64/redhat-linux-build/../glib/gmain.c:3480:28
  13: g_main_context_dispatch_unlocked
             at /usr/src/debug/glib2-2.78.3-1.1.tracy1.fc39.x86_64/redhat-linux-build/../glib/gmain.c:4331:7
  14: g_main_context_iterate_unlocked.isra.0
             at /usr/src/debug/glib2-2.78.3-1.1.tracy1.fc39.x86_64/redhat-linux-build/../glib/gmain.c:4401:5
  15: g_main_context_iteration
             at /usr/src/debug/glib2-2.78.3-1.1.tracy1.fc39.x86_64/redhat-linux-build/../glib/gmain.c:4466:12
  16: g_application_run
             at /usr/src/debug/glib2-2.78.3-1.1.tracy1.fc39.x86_64/redhat-linux-build/../gio/gapplication.c:2577:7
  17: gio::application::ApplicationExtManual::run_with_args
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gio-0.18.4/src/application.rs:29:13
  18: gio::application::ApplicationExtManual::run
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gio-0.18.4/src/application.rs:22:9
  19: ashpd_demo::application::Application::run
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/src/application.rs:238:9
  20: ashpd_demo::main
             at /var/home/yalter/source/rs/ashpd/ashpd-demo/src/main.rs:37:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
```

**Comment by bilelmoussaoui** [comment]
Well... The API doesn't propagate the gerror anywhere. I guess we would have to manually implement the function and convert a NULL handle to an error.

**Comment by YaLTeR** [comment]
Thanks!

**Comment by YaLTeR** [comment]
I patched ashpd-demo to use git gtk-rs and it works perfectly now.

**Comment by sdroege** [comment]
> I guess we would have to manually implement the function and convert a NULL handle to an error.

There's a `null_return_is_error` configuration for the Gir.toml :)
