### ISSUE TITLE
Regression: ApplicationBuilder::build() requires gtk::init() to be called

### ISSUE THREAD

**Issue by felinira** [gtk-rs/gtk4-rs#1888]
**Bug description**

Since the latest regen 162635636428b6287d1156ee9e2ae3cdff28a630 [`ApplicationBuilder::build()`](https://github.com/gtk-rs/gtk4-rs/blame/main/gtk4/src/auto/application.rs#L104) requires gtk::init to be called beforehand. But gtk::Application is generally supposed to be able to run without calling gtk::init(), it will call it itself during its startup routine.

This causes a regression in various examples (and probably a lot of application code in the wild)

**Backtrace**

```sh
> RUST_BACKTRACE=1 cargo run --bin list_box_model --manifest-path examples/Cargo.toml --features im-rc
    Skipping git submodule `https://github.com/gtk-rs/gir` due to update strategy in .gitmodules
    Skipping git submodule `https://github.com/gtk-rs/gir-files` due to update strategy in .gitmodules
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/list_box_model`
thread 'main' panicked at gtk4/src/auto/application.rs:104:9:
GTK has not been initialized. Call `gtk::init` first.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: gtk4::auto::application::ApplicationBuilder::build
             at ./gtk4/src/rt.rs:32:17
   3: list_box_model::main
             at ./examples/list_box_model/main.rs:16:23
   4: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bilelmoussaoui** [comment]
aha, the assertion happens before the post build hook 
https://github.com/gtk-rs/gtk4-rs/blob/main/gtk4/src/auto/application.rs#L104-L108, we should probably skip it for the cases where you have a hook I guess?
