### ISSUE TITLE
[BUG] TreeView panics with: assertion failed: ::glib::types::instance_of::<Self>(ptr as *const _)

### ISSUE THREAD

**Issue by andy128k** [gtk-rs/gtk4-rs#584]
## TreeView::selection() panics during destruction

`TreeView::selection()` assumes that a selection always exists. This is not true during a disposal of a tree view.

1. selection is destroyed first
2. then model is set to `NULL`
3. this causes a signal `cursor-changed`
4. there is no selection inside of signal handler. `TreeView::selection()` panics.

Checking of `Widget::in_destruction` doesn't help, because this happens earlier than `in_destruction` is set.

## Example

```rust
use gtk4::prelude::*;

fn window(app: &gtk4::Application) -> gtk4::ApplicationWindow {
    let model = gtk4::ListStore::new(&[gtk4::glib::Type::I32]);

    let tv = gtk4::TreeView::builder().model(&model).build();
    tv.connect_cursor_changed(|tv| {
        let _selection = tv.selection(); // panics here
    });

    let window = gtk4::ApplicationWindow::builder()
        .application(app)
        .child(&tv)
        .build();
    window
}

fn main() {
    let app = gtk4::Application::new(None, Default::default());
    app.connect_activate(|app| {
        let win = window(app);
        win.show();
    });
    app.run();
}
```

Same code with Gtk 3 runs without panicing.

## Backtrace

```
thread 'main' panicked at 'assertion failed: ::glib::types::instance_of::<Self>(ptr as *const _)', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.2.0/src/auto/tree_selection.rs:19:1
stack backtrace:
   0:     0x563b8d41aeb0 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x563b8d41aeb0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563b8d41aeb0 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563b8d41aeb0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x563b8d4348bc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x563b8d4197d5 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x563b8d41caeb - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563b8d41caeb - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563b8d41caeb - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x563b8d41c5c1 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x563b8d41d1b4 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x563b8d41cc67 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:517:13
  12:     0x563b8d41b3ac - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563b8d41cbf9 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x563b8d3dee21 - core::panicking::panic_fmt::h12a3a3c256485fca
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x563b8d3ded6d - core::panicking::panic::h344f23ad26057b48
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:50:5
  16:     0x563b8d3e4b9f - <gtk4::auto::tree_selection::TreeSelection as glib::translate::FromGlibPtrNone<*mut gtk4_sys::GtkTreeSelection>>::from_glib_none::h30a8b70860fa4860
                               at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.5/src/object.rs:770:17
  17:     0x563b8d3e591e - glib::translate::from_glib_none::h9000f2abffd79ab3
                               at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.5/src/translate.rs:1368:5
  18:     0x563b8d3dfcee - <O as gtk4::auto::tree_view::TreeViewExt>::selection::h2ca83b79fa632ecc
                               at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.2.0/src/auto/tree_view.rs:1557:13
  19:     0x563b8d3e1400 - tree_selection_bug::window::{{closure}}::h89963697da9ba08c
                               at /home/andy/projects/rust/gtk-rs/tree-selection-bug/src/main.rs:8:26
  20:     0x563b8d3dfcaa - <O as gtk4::auto::tree_view::TreeViewExt>::connect_cursor_changed::cursor_changed_trampoline::h42b3624c700405c2
                               at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.2.0/src/auto/tree_view.rs:2253:13
  21:     0x7fe05c8748f9 - <unknown>
  22:     0x7fe05c88d0d8 - g_signal_emit_valist
  23:     0x7fe05c88d2cf - g_signal_emit
  24:     0x7fe05c31346e - gtk_tree_view_set_model
  25:     0x7fe05c31380e - <unknown>
  26:     0x7fe05c8795e3 - g_object_unref
  27:     0x7fe05c3486b6 - <unknown>
  28:     0x7fe05c0f4f3b - <unknown>
  29:     0x7fe05c8795e3 - g_object_unref
  30:     0x7fe05c205bf6 - <unknown>
  31:     0x7fe05c33ed5c - <unknown>
  32:     0x7fe05c430979 - <unknown>
  33:     0x7fe05c45756d - <unknown>
  34:     0x7fe05c8748f9 - <unknown>
  35:     0x7fe05c88c484 - g_signal_emit_valist
  36:     0x7fe05c88d2cf - g_signal_emit
  37:     0x7fe05c45aba6 - <unknown>
  38:     0x7fe05c46b4fa - <unknown>
  39:     0x7fe05bb7bd0b - g_main_context_dispatch
  40:     0x7fe05bb7bfb8 - <unknown>
  41:     0x7fe05bb7c06f - g_main_context_iteration
  42:     0x7fe05bd427d5 - g_application_run
  43:     0x563b8d3e2866 - <O as gio::application::ApplicationExtManual>::run_with_args::h0291217653945e0c
                               at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.14.6/src/application.rs:30:13
  44:     0x563b8d3e292c - <O as gio::application::ApplicationExtManual>::run::h80521cb4e03f7f28
                               at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.14.6/src/application.rs:23:9
  45:     0x563b8d3e1656 - tree_selection_bug::main::hef5cdd557a1ba602
                               at /home/andy/projects/rust/gtk-rs/tree-selection-bug/src/main.rs:24:5
  46:     0x563b8d3e2b7b - core::ops::function::FnOnce::call_once::hdd82ec13a3efdb49
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  47:     0x563b8d3e2f7e - std::sys_common::backtrace::__rust_begin_short_backtrace::hb95ed5cc8413f099
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:125:18
  48:     0x563b8d3e1321 - std::rt::lang_start::{{closure}}::h979720532c37cffc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:63:18
  49:     0x563b8d41d6ba - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha9408abe89f69dc4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  50:     0x563b8d41d6ba - std::panicking::try::do_call::h5b0cc9e9102acb65
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  51:     0x563b8d41d6ba - std::panicking::try::hddc7f8229138b3ba
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  52:     0x563b8d41d6ba - std::panic::catch_unwind::hfa401ff8bab2986e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  53:     0x563b8d41d6ba - std::rt::lang_start_internal::{{closure}}::h8163422320d11405
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  54:     0x563b8d41d6ba - std::panicking::try::do_call::hc742cc7bb4f0fb20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  55:     0x563b8d41d6ba - std::panicking::try::ha37d8d2dd1acf7d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  56:     0x563b8d41d6ba - std::panic::catch_unwind::h8a5381d5ecf437bc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  57:     0x563b8d41d6ba - std::rt::lang_start_internal::h7e2cee8c90d4a4d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  58:     0x563b8d3e12f0 - std::rt::lang_start::h22d2fd5d31d94478
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:62:5
  59:     0x563b8d3e16bc - main
  60:     0x7fe05b7efe4a - __libc_start_main
  61:     0x563b8d3df57a - _start
  62:                0x0 - <unknown>

```

**Comment by sdroege** [comment]
That means that here https://github.com/gtk-rs/gtk4-rs/blob/c9f37ed7077ba207e0d3e17247e929c4f1a69bd6/gtk4/src/auto/tree_view.rs#L1557-L1559

the return value is not actually a `GtkTreeSelection` for some reason, but something else.

**Comment by sdroege** [comment]
More specifically, it's `NULL`. That function needs to be `nullable` in its return type.

Do you want to provide a PR and also an MR for GTK (the C library) to annotate it as `nullable`?

**Comment by bilelmoussaoui** [comment]
I believe the gtk should be done on gtk side

**Comment by sdroege** [comment]
Can someone report it there with a testcase?
