### ISSUE TITLE
[HELP] gtk4 crate not being recognized in sample code

### ISSUE THREAD

**Issue by jethro-djan** [gtk-rs/gtk4-rs#624]
I am trying to run this code listed here in [Hello World](https://gtk-rs.org/gtk4-rs/stable/latest/book/hello_world.html) part of the book
```rust
use gtk::prelude::*;
use gtk::{Application, ApplicationWindow};

fn main() {
    // Create a new application
    let app = Application::builder()
        .application_id("org.gtk.example")
        .build();

    // Connect to "activate" signal of `app`
    app.connect_activate(build_ui);

    // Run the application
    app.run();
}

fn build_ui(app: &Application) {
    // Create a window and set the title
    let window = ApplicationWindow::builder()
        .application(app)
        .title("My GTK App")
        .build();

    // Present window to the user
    window.present();
}
```
This is my `Cargo.toml` file
```Cargo
[package]
name = "my-gtk-app"
version = "0.1.0"
edition = "2018"

[dependencies]
gtk = { version = "0.2", package = "gtk4" }
```

The book recommends using Cargo and meson to compile and run the code. So I first do `cargo run` and get 
```sh
Running `target/debug/my-gtk-app`
[1]    88245 segmentation fault  cargo run
```
Then I proceed to use `meson setup builddir` and `meson compile -C builddir`. I get
```sh
ninja: Entering directory `builddir'
[1/1] Compiling Rust source ../src/main.rs
FAILED: main
rustc -C linker=cc --color=always --crate-type bin --crate-name main -g --emit dep-info=main.d --emit link -o main -L/usr/local/Cellar/gtk4/4.4.0/lib -L/usr/local/Cellar/pango/1.48.10/lib -L/usr/local/Cellar/harfbuzz/3.0.0/lib -L/usr/local/Cellar/gdk-pixbuf/2.42.6/lib -L/usr/local/Cellar/cairo/1.16.0_5/lib -L/usr/local/Cellar/graphene/1.10.6/lib -L/usr/local/Cellar/glib/2.70.0_1/lib -L/usr/local/opt/gettext/lib -l dylib=gtk-4 -l dylib=pangocairo-1.0 -l dylib=pango-1.0 -l dylib=harfbuzz -l dylib=gdk_pixbuf-2.0 -l dylib=cairo-gobject -l dylib=cairo -l dylib=graphene-1.0 -l dylib=gio-2.0 -l dylib=gobject-2.0 -l dylib=glib-2.0 -l dylib=intl ../src/main.rs
error[E0433]: failed to resolve: maybe a missing crate `gtk`?
 --> ../src/main.rs:1:5
  |
1 | use gtk::prelude::*;
  |     ^^^ maybe a missing crate `gtk`?

error[E0432]: unresolved import `gtk`
 --> ../src/main.rs:2:5
  |
2 | use gtk::{Application, ApplicationWindow};
  |     ^^^ maybe a missing crate `gtk`?

error: aborting due to 2 previous errors
```
I have already tried to ask a question on StackOverflow [here](https://stackoverflow.com/questions/69600271/missing-crate-error-even-though-present-in-cargo-toml). Somebody commented that the compiler seems to be ignoring my `Cargo.toml' file. Here is my `meson.build`
```meson
project(
  'my-gtk-app',
  'rust',
  version : '0.1',
)

cargo_sources = files(
  'Cargo.toml',
  'Cargo.lock',
)

gtk = dependency('gtk4', version: '>= 4.0.0')
executable('main', 'src/main.rs', dependencies : gtk)
```
What am I missing? I am on MacOS.

**Comment by Hofer-Julian** [comment]
You should follow the template (https://gitlab.gnome.org/bilelmoussaoui/gtk-rust-template) as described in the book.

Nobody tested that one on macOS though. Please report back if it works for you.

Alternatively, using cargo only should work fine.

**Comment by jethro-djan** [comment]
I tried that initially but I can only follow up to initializing the project using the `create-project.py` script. I cannot use Flatpac since I am not on linux. Hence my need to go my own way on getting it to run.

**Comment by sdroege** [comment]
> Running GTK4 applications on macOS seems to crash. Does the `gtk4-demo` from GTK work for you? If that also doesn't work, please report this to https://gitlab.gnome.org/GNOME/gtk/-/issues/new with a backtrace of the crash.

Also is this with an Apple M1 CPU?
And if `gtk4-demo` works, can you run `target/debug/my-gtk-app` in `lldb` or `gdb` to get a backtrace of the crash?

**Comment by sdroege** [comment]
> At this point it tries to run and then it crashes with a crash report from my OS. So I thought maybe the problem was my gtk installation. If I compile sample code using c from GTK it works fine. I am on intel MacBook Air.

Ok, then please run `target/debug/my-gtk-app` in a debugger and get a backtrace :)

> Also I don't know which `gtk4-demo` you speak of. Is it the one on their main website [here](https://www.gtk.org/)?

The one that comes with GTK4.

**Comment by Hofer-Julian** [comment]
@jethro-djan your example above suggests that you try to use the Rust support of meson.
That unfortunately only works for simple cases with no dependencies.

Please give the template another try.
At least in theory it should work on macOS as well.
Flatpak is not required.

**Comment by jethro-djan** [comment]
@Hofer-Julian @sdroege Thank you for your help. I think I have figured out the problem. I discovered from (https://www.gtk.org/docs/installations/macos/) that the process they give to install it on mac seems to install gtk+3.24 instead on my machine. Maybe I didn't follow the instructions too well. I used the `gtk-osx-setup.sh` shell script and I should have understood from the get-go from here (https://wiki.gnome.org/Projects/GTK/OSX/Building) that it currently works for only GTK3. 

I'll try this journey again once I get my hands on a linux machine (in the future somewhere...) :)

**Comment by jethro-djan** [comment]
Already did. When I run with `meson compile -C builddir` in the generated project I get 
```shell
/path/to/dir/gtk-rust-template-master/hello-gtk/meson: No such file or directory
```
However, when I use `cargo run`, I get an error with the following backtrace
```shell
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
     Running `target/debug/hello-gtk`
thread 'main' panicked at 'Could not load gresource file: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/path/to/dir/resources.gresource”: open() failed: No such file or directory" }', src/main.rs:25:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::expect
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1241:23
   4: hello_gtk::main
             at ./src/main.rs:25:15
   5: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
```

**Comment by bilelmoussaoui** [comment]
that's probably because the template needs changes to work out the box in macos. I would suggest using plain cargo for now and figure out the rest later. I don't have access to a macos machine so i can't do much to help here sadly :/

**Comment by jethro-djan** [comment]
okay cool. When I create my own project using `cargo` and add the `gtk4` dependency into the `Cargo.toml` file, running it always gives me
```shell
[1]  64917 segmentation fault  cargo run
```
Any idea why? I can't seem to find any information on `segmentation faults`.

**Comment by bilelmoussaoui** [comment]
You will need to run your binary through a debugger to figure out what's going on.

**Comment by jethro-djan** [comment]
@sdroege as at the time you mentioned it, I wasn't familiar with it. I have been trying to learn a bit more about it so I can get back to you. So far this is what I did
-  I run `rust-lldb target/debug/my-gtk-app` in `my-gtk-app project`. This is what I get:
 ```shell
- (lldb) command script import "/Users/name/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/etc/lldb_lookup.py"
(lldb) command source -s 0 '/Users/name/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/etc/lldb_commands'
Executing commands in '/Users/name/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/etc/lldb_commands'.
(lldb) type synthetic add -l lldb_lookup.synthetic_lookup -x ".*" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)String$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^&(mut )?str$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^&(mut )?\\[.+\\]$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::ffi::([a-z_]+::)+)OsString$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Vec<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)VecDeque<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)BTreeSet<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)BTreeMap<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::collections::([a-z_]+::)+)HashMap<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(std::collections::([a-z_]+::)+)HashSet<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Rc<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(alloc::([a-z_]+::)+)Arc<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)Cell<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)Ref<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)RefMut<.+>$" --category Rust
(lldb) type summary add -F lldb_lookup.summary_lookup  -e -x -h "^(core::([a-z_]+::)+)RefCell<.+>$" --category Rust
(lldb) type category enable Rust
(lldb) target create "target/debug/my-gtk-app"
Current executable set to '/path/to/dir/my-gtk-app/target/debug/my-gtk-app' (x86_64).
(lldb)
```
- I don't even know where to set the breakpoints (that's all I can do so far when I use `lldb`) given the compiler did not give any helpful messages

Does this help you in any way @sdroege @bilelmoussaoui ?
