### ISSUE TITLE
[BUG] search_entry.key_capture_widget().grab_focus() causes panic

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk4-rs#774]
**Bug description**

 ```rust
 search_entry.key_capture_widget().grab_focus();
```
will cause a panic

**Backtrace**
```
thread 'main' panicked at 'assertion failed: ::glib::types::instance_of::<Self>(ptr as *const _)', /home/lollo/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.3.1/src/auto/widget.rs:39:1
stack backtrace:
   0:     0x55f713c855f6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1ef07120adb99796
   1:     0x55f713c9689c - core::fmt::write::h59cc4b3dea155cce
   2:     0x55f713c736e5 - std::io::Write::write_fmt::he7e4fb4b70c5207a
   3:     0x55f713c7d550 - std::panicking::default_hook::{{closure}}::h67c88fba3a1757d9
   4:     0x55f713c7d0f1 - std::panicking::default_hook::had51536d17f32530
   5:     0x55f713c7db03 - std::panicking::rust_panic_with_hook::hcdfd560c4f6afa56
   6:     0x55f713c85ab2 - std::panicking::begin_panic_handler::{{closure}}::h5e7abb77afe4762c
   7:     0x55f713c85744 - std::sys_common::backtrace::__rust_end_short_backtrace::hb15a1d01c910931c
   8:     0x55f713c7d642 - rust_begin_unwind
   9:     0x55f713c390c1 - core::panicking::panic_fmt::h4b7f7457475b4299
  10:     0x55f713c3900d - core::panicking::panic::hf2a1a8726f570f0d
  11:     0x55f713c4234f - <gtk4::auto::widget::Widget as glib::translate::FromGlibPtrNone<*mut gtk4_sys::GtkWidget>>::from_glib_none::h1638a943298776c6
                               at /home/lollo/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/object.rs:770:17
  12:     0x55f713c4133e - glib::translate::from_glib_none::h9ad2c3914246454b
                               at /home/lollo/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/translate.rs:1368:5
  13:     0x55f713c441de - gtk4::auto::search_entry::SearchEntry::key_capture_widget::hee126b1d2c75432f
                               at /home/lollo/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.3.1/src/auto/search_entry.rs:55:13
  14:     0x55f713c3f67a - search_focus_gtk_crash::on_activate::ha1cb3b3f06be3e1f
                               at /home/lollo/Shit/search_focus_gtk_crash/src/main.rs:19:5
  15:     0x55f713c3a888 - core::ops::function::Fn::call::h62181aacc4a644e6
                               at /build/rustc-1.56.1-src/library/core/src/ops/function.rs:70:5
  16:     0x55f713c3abcb - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::h1df020232a51af4f
                               at /home/lollo/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.14.8/src/auto/application.rs:600:13
  17:     0x7f54cece364f - g_closure_invoke
  18:     0x7f54cecf537b - signal_emit_unlocked_R.isra.0
  19:     0x7f54cecfba5f - g_signal_emit_valist
  20:     0x7f54cecfbfbf - g_signal_emit
  21:     0x7f54ce1b52a8 - g_application_real_local_command_line
  22:     0x7f54ce1b541e - g_application_run
  23:     0x55f713c3ad17 - <O as gio::application::ApplicationExtManual>::run_with_args::h6d505f82db3a033d
                               at /home/lollo/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.14.8/src/application.rs:30:13
  24:     0x55f713c3ae06 - <O as gio::application::ApplicationExtManual>::run::h31747d5ff35df087
                               at /home/lollo/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.14.8/src/application.rs:23:9
  25:     0x55f713c3f77f - search_focus_gtk_crash::main::hafb6401390e2323c
                               at /home/lollo/Shit/search_focus_gtk_crash/src/main.rs:29:5
  26:     0x55f713c3a8bb - core::ops::function::FnOnce::call_once::h10817535cef05a48
                               at /build/rustc-1.56.1-src/library/core/src/ops/function.rs:227:5
  27:     0x55f713c3b0ae - std::sys_common::backtrace::__rust_begin_short_backtrace::h9b7ce8ee212c47f9
                               at /build/rustc-1.56.1-src/library/std/src/sys_common/backtrace.rs:125:18
  28:     0x55f713c3e5d1 - std::rt::lang_start::{{closure}}::he36ca67e980ea993
                               at /build/rustc-1.56.1-src/library/std/src/rt.rs:63:18
  29:     0x55f713c7f781 - std::rt::lang_start_internal::hc2cb966a7a4d713d
  30:     0x55f713c3e5a0 - std::rt::lang_start::haf3477d172be1e0e
                               at /build/rustc-1.56.1-src/library/std/src/rt.rs:62:5
  31:     0x55f713c3f80c - main
  32:     0x7f54cdc7d780 - __libc_start_main
  33:     0x55f713c3936a - _start
                               at /build/glibc-2.33/csu/../sysdeps/x86_64/start.S:120
  34:                0x0 - <unknown>
```

**Minimal example to reproduce**
I took the first example from gtk.org and added two lines to create a search entry and cause the crash

```rust
// glib and other dependencies are re-exported by the gtk crate
use gtk4 as gtk;
use gtk::glib;
use glib::clone;
use gtk::prelude::*;

// When the application is launched…
fn on_activate(application: &gtk::Application) {
    // … create a new window …
    let window = gtk::ApplicationWindow::new(application);
    // … with a button in it …
    let button = gtk::Button::with_label("Hello World!");
    // … which closes the window when clicked
    button.connect_clicked(clone!(@weak window => move |_| window.close()));
    window.set_child(Some(&button));
    window.present();

    // HERE BE DRAGONS
    let search_entry = gtk::SearchEntry::new();
    search_entry.key_capture_widget().grab_focus();
}

fn main() {
    // Create a new application with the builder pattern
    let app = gtk::Application::builder()
        .application_id("com.github.gtk-rs.examples.basic")
        .build();
    app.connect_activate(on_activate);
    // Run the application
    app.run();
}
```

**Comment by ranfdev** [comment]
I had also tried grabbing the focus after the widget was mapped, but that still didn't work.

Then on the vala docs I've found "Grabbing the focus immediately after creating the widget will likely fail and cause critical warnings.".

So in my app I'm now doing
```rust
glib::source::idle_add_local(move || {
            search_entry.grab_focus();
            Continue(false)
}
```
and it correctly grabs the focus.

doing `search_entry.key_capture_widget().grab_focus()` still causes a panic, even doing `idle_add`, so I'm keeping this open

**Comment by sdroege** [comment]
That sounds like a missing annotation in the C code: the return value should be marked `nullable`. Especially because the setter has the key capture widget marked as `nullable`.

See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4286

That would mean that on the bindings side this would have to return an `Option`.
