### ISSUE TITLE
[BUG] gdk::Display::name panics on macOS

### ISSUE THREAD

**Issue by andy128k** [gtk-rs/gtk4-rs#868]
```rust
use gtk4::prelude::*;

fn main() {
    gtk4::init().unwrap();
    let display = gtk4::gdk::Display::default().unwrap();
    println!("Display name = {}", display.name());
}
```

**Backtrace**

```

thread 'main' panicked at 'assertion failed: !ptr.is_null()', /Users/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.5/src/gstring.rs:356:9
stack backtrace:
   0:        0x1021e5161 - std::backtrace_rs::backtrace::libunwind::trace::h47a7835575e4d9f3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1021e5161 - std::backtrace_rs::backtrace::trace_unsynchronized::he8690599afcb5399
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1021e5161 - std::sys_common::backtrace::_print_fmt::h0617b83dce07f61f
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x1021e5161 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c059b532d34bdd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x1021f916b - core::fmt::write::hefb311138778afb5
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:        0x1021e29ea - std::io::Write::write_fmt::h0e0ed87b18ae870c
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:        0x1021e6685 - std::sys_common::backtrace::_print::hcb332ccba1b9e587
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x1021e6685 - std::sys_common::backtrace::print::h8f35339db66741dd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x1021e6685 - std::panicking::default_hook::{{closure}}::h43f0e51e5825bd5b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:        0x1021e626f - std::panicking::default_hook::ha1c3473cbcf391f7
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:        0x1021e6d70 - std::panicking::rust_panic_with_hook::h0db3c4ba5fb4dc12
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:        0x1021e67e4 - std::panicking::begin_panic_handler::{{closure}}::hc6d8c92efeef5a19
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:500:13
  12:        0x1021e55d7 - std::sys_common::backtrace::__rust_end_short_backtrace::h7ffb59e898e02a83
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x1021e677a - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:        0x1021ff61f - core::panicking::panic_fmt::h7d73f67464d78916
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:        0x1021ff577 - core::panicking::panic::h9721d5a8c5d33ad7
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
  16:        0x1021c65a5 - <glib::gstring::GString as glib::translate::FromGlibPtrNone<*const u8>>::from_glib_none::ha3542f75dfc37347
                               at /Users/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.5/src/gstring.rs:356:9
  17:        0x1021c5f18 - glib::translate::from_glib_none::hfb725c1cc5bb3a64
                               at /Users/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.5/src/translate.rs:1426:5
  18:        0x1021c6608 - <glib::gstring::GString as glib::translate::FromGlibPtrNone<*const i8>>::from_glib_none::h17d487956a62b9cb
                               at /Users/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.5/src/gstring.rs:367:9
  19:        0x1021c5ec8 - glib::translate::from_glib_none::h695b8aaa49e39ef9
                               at /Users/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.5/src/translate.rs:1426:5
  20:        0x1021c4fcf - <O as gdk4::auto::display::DisplayExt>::name::h111746e912dce794
                               at /Users/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/gdk4-0.4.6/src/auto/display.rs:253:18
  21:        0x1021c4d0a - d::main::h78b55180ad52657f
                               at /private/tmp/d/src/main.rs:6:35
  22:        0x1021c4c0e - core::ops::function::FnOnce::call_once::h16099e45e440d1b6
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  23:        0x1021c4ff1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2a400a1eabe627a0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123:18
  24:        0x1021c4f64 - std::rt::lang_start::{{closure}}::h09e7232e6b78e369
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:145:18
  25:        0x1021e4e0f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h366f85254a0aedbd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  26:        0x1021e4e0f - std::panicking::try::do_call::hcd7d6ba18808215d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  27:        0x1021e4e0f - std::panicking::try::h8b7328b76a891d08
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  28:        0x1021e4e0f - std::panic::catch_unwind::h63bbd5ef51caa433
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  29:        0x1021e4e0f - std::rt::lang_start_internal::{{closure}}::h2efd4ac38212ab36
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  30:        0x1021e4e0f - std::panicking::try::do_call::hfdf1ca9f7283bb6b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  31:        0x1021e4e0f - std::panicking::try::h5e8a1aa20c127c08
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  32:        0x1021e4e0f - std::panic::catch_unwind::he9efa865311db8e6
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  33:        0x1021e4e0f - std::rt::lang_start_internal::hb74872162e3d56c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  34:        0x1021c4f3e - std::rt::lang_start::ha61d8534228235e7
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:144:17
  35:        0x1021c4df6 - <unknown>
                               at /private/tmp/d/src/main.rs:7:2
```

**Comment by bilelmoussaoui** [comment]
It needs to be marked as nullabe upstream

**Comment by sdroege** [comment]
Or maybe it should get a dummy name instead.

**Comment by bilelmoussaoui** [comment]
Should hopefully be fixed upstream once https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4453 is merged

**Comment by bilelmoussaoui** [comment]
Should be fixed in the next release of gtk, feel free to do a test build :-)
