### ISSUE TITLE
[BUG] Incorrect behavior of `gtk::HeaderBar::remove`

### ISSUE THREAD

**Issue by cofee-on-the-desk** [gtk-rs/gtk4-rs#954]
**Bug description**

If you remove the title widget with `gtk::HeaderBar::remove`, you cannot add it again.

The following code panics on the last assert:

```rust
use gtk::prelude::{ApplicationExt, ApplicationExtManual, WidgetExt};

fn main() {
    let app = gtk::Application::builder()
        .application_id("org.gtk-rs.example")
        .build();

    app.connect_activate(|_| {
        let header = gtk::HeaderBar::default();
        let w = gtk::Box::default();

        header.set_title_widget(Some(&w));
        assert!(w.parent().is_some());

        //header.set_title_widget(None::<&gtk::Widget>);
        header.remove(&w);
        assert!(w.parent().is_none());

        header.set_title_widget(Some(&w));
        assert!(w.parent().is_some());
    });

    app.run();
}
```

It does not panic if you remove the comment, and add a comment the line below.

**Backtrace**

Should not matter here, but I'll add it for completeness.

```
thread 'main' panicked at 'assertion failed: w.parent().is_some()', src/main.rs:20:9
stack backtrace:
   0:     0x55ec25376fdc - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ec25376fdc - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ec25376fdc - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55ec25376fdc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55ec2539146c - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x55ec253748b5 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x55ec25378730 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55ec25378730 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55ec25378730 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x55ec253782e5 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x55ec25378de4 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:     0x55ec25378892 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:500:13
  12:     0x55ec25377484 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55ec25378829 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:     0x55ec2533ebf1 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:     0x55ec2533eb3d - core::panicking::panic::h86fc01e270142a61
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
  16:     0x55ec25341ea2 - test::main::{{closure}}::h9ad76ee280749155
                               at /home/max/Programming/rust/relmtest/src/main.rs:20:9
  17:     0x55ec2534097b - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::hc0a68a1767ef0eb5
                               at /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.15.6/src/auto/application.rs:604:13
  18:     0x7fe29d5fec7f - g_closure_invoke
  19:     0x7fe29d61b126 - <unknown>
  20:     0x7fe29d61c9ea - g_signal_emit_valist
  21:     0x7fe29d61cc03 - g_signal_emit
  22:     0x7fe29cb87188 - <unknown>
  23:     0x7fe29cb87366 - g_application_run
  24:     0x55ec25340ac7 - <O as gio::application::ApplicationExtManual>::run_with_args::h62d3ad4a8da3e922
                               at /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.15.6/src/application.rs:30:13
  25:     0x55ec25340bb6 - <O as gio::application::ApplicationExtManual>::run::h82d80b30f576d5b4
                               at /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.15.6/src/application.rs:23:9
  26:     0x55ec2534204f - test::main::h2fc614e623760185
                               at /home/max/Programming/rust/relmtest/src/main.rs:23:5
  27:     0x55ec25340e8b - core::ops::function::FnOnce::call_once::h605798c350e31b09
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  28:     0x55ec2534102e - std::sys_common::backtrace::__rust_begin_short_backtrace::h677b5609c4ba3996
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123:18
  29:     0x55ec25341511 - std::rt::lang_start::{{closure}}::hf58880fed7056abf
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:145:18
  30:     0x55ec25376c6b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7e688d7cdfeb7e00
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  31:     0x55ec25376c6b - std::panicking::try::do_call::h4be824d2350b44c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  32:     0x55ec25376c6b - std::panicking::try::h0a6fc7affbe5088d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  33:     0x55ec25376c6b - std::panic::catch_unwind::h22c320f732ec805e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  34:     0x55ec25376c6b - std::rt::lang_start_internal::{{closure}}::hd38309c108fe679d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  35:     0x55ec25376c6b - std::panicking::try::do_call::h8fcaf501f097a28e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  36:     0x55ec25376c6b - std::panicking::try::h20e906825f98acc1
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  37:     0x55ec25376c6b - std::panic::catch_unwind::h8c5234dc632124ef
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  38:     0x55ec25376c6b - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  39:     0x55ec253414e0 - std::rt::lang_start::hd6ff14e55febab2a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:144:17
  40:     0x55ec253420bc - main
  41:     0x7fe29c775560 - __libc_start_call_main
  42:     0x7fe29c77560c - __libc_start_main_alias_1
  43:     0x55ec2533f315 - _start
  44:                0x0 - <unknown>
```

**Comment by sdroege** [comment]
That would be a bug in GTK. Can you report it at https://gitlab.gnome.org/GNOME/gtk/-/issues/new/ ? Thanks
